# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: gis
#    ports:
#      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    image: gis:latest
    container_name: gis
    build: .
    ports:
      - 8000:8000
    environment:
      - SQL_HOST=db
    depends_on:
      - db

