# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raffle.Ticket'),
        ),
    ]
