# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0005_auto_20170804_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
