# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('accounts', '0003_auto_20170718_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Address')),
                ('google_id', models.CharField(max_length=255)),
            ],
            bases=('address.address',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address'),
        ),
    ]
