# Generated by Django 3.0.5 on 2020-04-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_locks', related_query_name='challenge_locks', to='scavenger_hunt.Challenge')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scavenger_hunt.Player')),
            ],
        ),
    ]
