# Generated by Django 3.0.5 on 2020-04-22 11:22

from django.db import migrations, models
import django.db.models.deletion
import scavenger_hunt.models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0002_penaltytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[(0, scavenger_hunt.models.Reward.Type['general']), (1, scavenger_hunt.models.Reward.Type['clue']), (2, scavenger_hunt.models.Reward.Type['praise']), (3, scavenger_hunt.models.Reward.Type['points']), (4, scavenger_hunt.models.Reward.Type['key']), (5, scavenger_hunt.models.Reward.Type['powers']), (6, scavenger_hunt.models.Reward.Type['promotion']), (7, scavenger_hunt.models.Reward.Type['completion']), (8, scavenger_hunt.models.Reward.Type['media'])], default='general', max_length=127)),
                ('description', models.TextField()),
                ('unique', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scavenger_hunt.Challenge')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scavenger_hunt.Player')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scavenger_hunt.Reward')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
