# Generated by Django 3.0.5 on 2020-04-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0002_lock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lock',
        ),
    ]
