# Generated by Django 3.0.5 on 2020-04-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0005_question_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['index', 'id'], 'permissions': [('access_challenge', 'Can access the challenge')]},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-created'], 'permissions': [('access_reward', 'Can access the reward')]},
        ),
    ]
